// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO62FVj__rDQaafwZoX7nmo7VFjAoK9tI',
    appId: '1:146721496403:web:c4763e8ce735267ffa55a6',
    messagingSenderId: '146721496403',
    projectId: 'mychatapp-dbef3',
    authDomain: 'mychatapp-dbef3.firebaseapp.com',
    storageBucket: 'mychatapp-dbef3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaSS1EfAgiuwoLcR9YvpSJwMrwqZqfSfo',
    appId: '1:146721496403:android:96af0d127bc8ed76fa55a6',
    messagingSenderId: '146721496403',
    projectId: 'mychatapp-dbef3',
    storageBucket: 'mychatapp-dbef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1yCcDM5YcVnYVWnVVjnJUNi6zSt67Kp8',
    appId: '1:146721496403:ios:826516f26f3bc117fa55a6',
    messagingSenderId: '146721496403',
    projectId: 'mychatapp-dbef3',
    storageBucket: 'mychatapp-dbef3.appspot.com',
    iosClientId: '146721496403-1486atg076uihhh9no9m0ltebetjdt4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1yCcDM5YcVnYVWnVVjnJUNi6zSt67Kp8',
    appId: '1:146721496403:ios:826516f26f3bc117fa55a6',
    messagingSenderId: '146721496403',
    projectId: 'mychatapp-dbef3',
    storageBucket: 'mychatapp-dbef3.appspot.com',
    iosClientId: '146721496403-1486atg076uihhh9no9m0ltebetjdt4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
